Ips 279 dynatrace dev environment
govuk-one-login/ipv-core-front pull request #1107
Opened 2023-10-13 17:07 UTC by vam-gds

## Proposed changes

### What changed
IPS-279 Dynatrace integration into core-front

	modified:   Dockerfile
	modified:   deploy/template.yaml

### Why did it change
IPS-279 Dynatrace integration into core-front

	modified:   Dockerfile
	modified:   deploy/template.yaml

### Issue tracking

- [IPS-279](https://govukverify.atlassian.net/browse/IPS-279)

## Checklists

### Environment variables or secrets

- [ ] No environment variables or secrets were added or changed

- [ ] Documented in the [README](./blob/main/README.md)
- [ ] Added to deployment repository
- [ ] Added to local startup repository

### Other considerations

- [ ] Update [README](./blob/main/README.md) with any new instructions or tasks

2023-10-13 17:09 UTC, two-first-names requested changes, later dismissed

2023-10-13 17:09 UTC, two-first-names commented on Dockerfile
> +COPY --from=khw46367.live.dynatrace.com/linux/oneagent-codemodules:<technology> / /
```suggestion
COPY --from=khw46367.live.dynatrace.com/linux/oneagent-codemodules-musl:java / /
```

2023-10-13 17:22 UTC, vam-gds commented on Dockerfile
> +COPY --from=khw46367.live.dynatrace.com/linux/oneagent-codemodules:<technology> / /
should be fixed now.

2023-11-22 06:16 UTC, vam-gds commented on deploy/template.yaml
> -                - !If [IsDevelopment, !Sub "development", !Ref "AWS::NoValue"]
please note this line failed in cfn-lint not sure why a !Sub was added to a string with no substitutions, can this be verified ?

2023-11-24 08:57 UTC, shivanshuit914 approved these changes

2023-11-24 10:00 UTC, merged