DFC-583 |  Implement passthrough headers package
govuk-one-login/ipv-core-front pull request #1444
Opened 2024-05-15 15:50 UTC by SophiaDWokoma

## Proposed changes

### What changed

### Why did it change

### Issue tracking

- [PYIC-XXXX](https://govukverify.atlassian.net/browse/PYIC-XXX)

## Checklists

### Environment variables or secrets

- [ ] No environment variables or secrets were added or changed

- [ ] Documented in the [README](./blob/main/README.md)
- [ ] Added to deployment repository
- [ ] Added to local startup repository

### Other considerations

- [ ] Update [README](./blob/main/README.md) with any new instructions or tasks

2024-05-16 07:34 UTC, di-fabs requested changes

2024-05-16 07:34 UTC, di-fabs commented on src/services/coreBackService.test.js
> +          "x-forwarded-for": "127.0.0.1",
I think it's risky to hardcoded an ip here. Maybe the value will not always be this one.
What you can do is to set a value line 43 and reuse it here.

Same comment applies for others line which defines an ip.

2024-05-16 14:14 UTC, SophiaDWokoma commented on src/services/coreBackService.test.js
> +          "x-forwarded-for": "127.0.0.1",
ok agreed , I have made the changes

2024-05-20 13:50 UTC, shivanshuit914 approved these changes

2024-05-20 14:28 UTC, di-fabs approved these changes

2024-05-20 14:32 UTC, merged