PYIC-7677: Allow expired documents - content updates & welsh translations
govuk-one-login/ipv-core-front pull request #1729
Opened 2024-12-05 14:04 UTC by AmritSidhu

## Proposed changes

### What changed

A policy decision has been made to allow certain expired documents to be accepted as evidence when a user is proving their identity with One Login.

As such this means we only have to make small content updates on a few pages:
- /page-ipv-identity-document-types
- /pyi-post-office
- /no-photo-id-abandon-find-another-way 
- /prove-identity-another-type-photo-id/en?context=drivingLicence
- /prove-identity-another-type-photo-id/en?context=passport
- /no-photo-id-security-questions-find-another-way
- /no-photo-id-exit-find-another-way

### Issue tracking

- [PYIC-7677](https://govukverify.atlassian.net/browse/PYIC-7677)

## Checklists

### Environment variables or secrets

- [ ] No environment variables or secrets were added or changed

2024-12-06 17:42 UTC, blakeyp commented on views/ipv/page/page-ipv-identity-document-types.njk
> +    {% for listItem in 'pages.pageIpvIdentityDocumentTypes.content.nonUkPassportRequirements' | translate({ returnObjects: true }) %}
I think nonUkPassportRequirements should be cardOrPermits here?

2024-12-09 14:29 UTC, DanCorderIPV requested changes

2024-12-09 14:29 UTC, DanCorderIPV commented on browser-tests/snapshot-tests/snapshot.spec.ts-snapshots/no-photo-id-exit-find-another-way-en-chromium-linux.jpeg
The figma has a couple of things that don't seem to be in here:
- The text "You can use a:" inside the expanded area
- The word "only" at the end of the last paragraph in the expanded area

2024-12-09 15:10 UTC, AmritSidhu commented on browser-tests/snapshot-tests/snapshot.spec.ts-snapshots/no-photo-id-exit-find-another-way-en-chromium-linux.jpeg
Good spots. 
In regards to the word 'only', i've based the translations off whats in the actual welsh translations spreadsheet which doesn't include that word. <- this was one of the discrepancies I mentioned i found during standup

2024-12-09 15:13 UTC, AmritSidhu commented on browser-tests/snapshot-tests/snapshot.spec.ts-snapshots/no-photo-id-exit-find-another-way-en-chromium-linux.jpeg
I will double check again with UCD if this is required or not

2024-12-10 09:15 UTC, DanCorderIPV commented on browser-tests/snapshot-tests/snapshot.spec.ts-snapshots/no-photo-id-exit-find-another-way-en-chromium-linux.jpeg
Thanks :)

2024-12-10 11:09 UTC, DanCorderIPV approved these changes

2024-12-16 10:31 UTC, merged