PYIC-2865 Modify FE for -Prove your identity another way- link to 'journey/claimIdentity'
govuk-one-login/ipv-core-front pull request #854
Opened 2023-05-26 16:35 UTC by rpayal

## Proposed changes
Modify FE for -Prove your identity another way- link to 'journey/claimIdentity'
### What changed
Modified FE for -Prove your identity another way- link to 'journey/claimIdentity'

### Why did it change

### Issue tracking

- [PYIC-2865](https://govukverify.atlassian.net/browse/PYIC-2865)

## Checklists

### Environment variables or secrets

- [ ] No environment variables or secrets were added or changed

- [ ] Documented in the [README](./blob/main/README.md)
- [ ] Added to deployment repository
- [ ] Added to local startup repository

### Other considerations

- [ ] Update [README](./blob/main/README.md) with any new instructions or tasks

2023-05-30 08:59 UTC, AmritSidhu submitted a review, later dismissed

2023-05-31 08:18 UTC, chris-dco requested changes
@rpayal is it possible to change `claimIdentity` to `claimedIdentity`? I am happy to approve then.

2023-05-31 09:00 UTC, chris-dco commented on src/views/ipv/page-multiple-doc-check.njk
> +                value: "next/claim-identity",
Should we do this on a feature flag? This is due to a comment on https://govukverify.atlassian.net/browse/PYIC-2834 where it says ‘How do we make this only available when the F2F is enabled???’

2023-06-02 08:42 UTC, chris-dco commented on src/views/ipv/page-multiple-doc-check.njk
> +                value: "next/claim-identity",
Also can you make it just "claimedIdentity".

2023-06-02 09:45 UTC, chris-dco commented on src/views/ipv/page-multiple-doc-check.njk
> +                value: "next/claimed-identity",
Also can you make it just "claimedIdentity" and feature flagged as this is only available in dev at the moment.

2023-06-02 10:22 UTC, chris-dco commented on src/views/ipv/page-multiple-doc-check.njk
> +                value: "next/claimed-identity",
Should we do this on a feature flag? This is due to a comment on https://govukverify.atlassian.net/browse/PYIC-2834 where it says ‘How do we make this only available when the F2F is enabled???’

2023-06-02 11:13 UTC, AmritSidhu approved these changes

2023-06-06 13:39 UTC, kerrr commented
I don't think we need this and it can be closed.

2023-06-06 13:41 UTC, rpayal commented
Not needed any more as done using state machine events. (so no FE change needed here)

2023-06-06 13:41 UTC, closed without merging